server:
  port: 8080

spring:
  datasource:
    username: root
    password: asdfre#@!
    url: jdbc:mysql://10.10.10.199:3306/goodsCenter_new?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
